### ISSUE TITLE
打开配置框设置生成参数 Preference –> Other Settings –> D8gerAutoCode  idea没有D8gerAutocode设置这一选项

### ISSUE THREAD

**Issue by 468336329Zc** [caofanCPU/D8gerAutoCode#4]
idea其它设置里 没有D8ger插件的设置选项。
idea版本是：#IU-191.7141.44,建于 May 7,2019
d8ger插件是2.5版本的

![Uploading image.png…]()

**Comment by 468336329Zc** [comment]
d8ger其他的功能倒是都能用，就是java web这个自动生成代码不能用 就是因为idea中没有D8gerAutocode这个其他设置。

**Comment by 468336329Zc** [comment]
> idea其它设置里 没有D8ger插件的设置选项。
> 
> idea版本是：#IU-191.7141.44,建于 May 7,2019
> 
> d8ger插件是2.5版本的
> 
> 
> 
> ![Uploading image.png…]()
> 
> 

也只能下载2.5版本的 通过官网下载其他版 无法安装到idea 出现 “not incompleteable ”错误

**Comment by caofanCPU** [comment]
hello，'D8gerAutocode'界面配置是从3.0版本才开始支持的。
我看你的 idea版本2019，已经比较旧了。因IDEA平台 2020版本对插件仓库进行过非兼容的升级，所以当时就选择了新版本的底层依赖。
你看你升级下IDEA版本？IDEA 2019会存在比较多的性能问题，IDEA 2020版本解决过一些，目前IDEA 最新稳定版是 2021.3.1  用着挺不错的。

如果是因为证书问题，建议你花点钱买个一年的证书，新版本功能效率能帮你省不少时间的。如果你是学生的话还有折扣
或者考虑申请开源许可证书，https://www.jetbrains.com/zh-cn/community/opensource/#support
